

Sub Main
    :Loop

    /tar ${Me}

    :ClearCursor 
    /if (${Cursor.ID}) { 
        /autoinventory 
        /goto :ClearCursor 
    } 

    /delay 5s
    /casting "Minor Healing" 1
    /delay 10s !${Me.Casting.ID}

    /delay 5s
    /casting "Endure Fire" 4
    /delay 10s !${Me.Casting.ID}

    /delay 5s
    /casting "Summon Food" 5
    /delay 10s !${Me.Casting.ID}

    /delay 5s
    /casting "Sense Animals" 3
    /delay 10s !${Me.Casting.ID}

    /goto :Loop
/return